[package]
name = "path_of_building_genetic_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.8", features = ["luajit52", "module"] }
rand = "0.8.5"

